#include <iostream>
#include <stdlib.h>
#include <time.h>
/*  ---------------------------------------------------------------------------------------------------------
                                        RPG BY USER MAXXBURN!
        This is your classic dungeon crawler RPG but with no level-ing up as of currently , no item drops and no equipment tab
        as of currently (Plan on adding stuff in the future).
        This will be eventually developed as a GUI , but since its a simple idea i decided to keep it text based.
        Gameplay is simple , use your abilities to survive and win against the dungeon monsters , each class has either a heal up
        or defense up . Both are there to help u survive , the same goes for their offensive abilities.


The game development is currently on PAUSE because im working on another software.
Contact for more info:
Discord(MaxxBurn#5098)
Twitter(MaxxBurnxd)
*/
using namespace std;
    string Player;
     //Tomb enemies
    string TombEnemy;
    //Desert Enemies
    string DesertEnemy; //End
    string PlayerSkillsArr[4];
    string Role;
    string skill1;
    string skill2;
    string skill3;
    string skill4;
    double skill1DMGPlayer;
    double skill2DMGPlayer;
    double skill3DMGPlayer;
    double skill4DMGPlayer;
    double skill1DMGEnemy;
    double skill2DMGEnemy;
    double skill3DMGEnemy;
    double Health;
    double HealthE;
    int AttackE;
    int LuckE;
    int MagicE;
    double DefenseE;
    int Attack;
    int Luck;
    int Magic;
    double Defense;

void Battle(double PlayerHP ,double PlayerDef , int PlayerAtk , int PlayerMagic ,double EnemyHp,double EnemyDef,
                int EnemyAtk , int EnemyMagic,double skill1DMGPlayer,double skill2DMGPlayer,double skill3DMGPlayer,
                double skill4DMGPlayer ,double skill1DMGEnemy,double skill2DMGEnemy ,double skill3DMGEnemy
                ,string ar[] , string ar2[])
    {
        cout<<"\n\nEnemy has : "<<HealthE<<" health!"<<endl;
        int i=0;
        int temp;
        cout<<"\n\n"<<"Type the number representing the ability to activate it , there's no cooldown on your abilities\n\n"<<endl;
        while(HealthE>0&&Health>0){

            for ( i; i<4; i++)
            {
                cout<<ar[i]<<endl;
            }
            cin>>temp;
            if ((Player=="Assassin"||Player=="assassin")&&temp==1)
            {
                cout<<"You activated Attack up! Your damage is increased by 50% "<<endl;
                skill3DMGPlayer= 0.5*skill3DMGPlayer+skill3DMGPlayer;
                skill4DMGPlayer= 0.5*skill4DMGPlayer+skill4DMGPlayer;
            }
            else if((Player=="Assassin"||Player=="assassin")&&temp==2)
            {
                if(Health==120||Health>120)
                {
                    cout<<"Your health is already 120! Your health wont be regenerated! "<<endl;
                }
                else
                {
                    cout<<"You activated regenerate health! Your health is regenerated by 40% "<<endl;
                    Health=Health * skill2DMGPlayer+Health;
                    cout<<"Your current health is : "<<Health<<endl;
                }
            }
            else if((Player=="Assassin"||Player=="assassin")&&temp==3)
            {
                cout<<"You have used Heart Stab "<<endl;
                cout<<"Enemy takes "<<(skill3DMGPlayer-DefenseE)<<" damage\n"<<endl;
                HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                if(HealthE<=0)
                    {
                        cout<<"Enemy has died\n"<<endl;
                    }
                else
                    {
                        cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                    }
            }
            else if((Player=="Assassin"||Player=="assassin")&&temp==4)
            {
                cout<<"You have used Throw Dagger! "<<endl;
                HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                cout<<"Enemy takes "<<skill3DMGPlayer-DefenseE<<" damage \n"<<endl;
                 if(HealthE<=0)
                    {
                        cout<<"Enemy has died\n"<<endl;
                    }
                else
                    {
                        cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                    }

            }
            else if ((Player=="Knight"||Player=="knight")&&temp==1)
            {
                cout<<"You activated Defense up! Your defense was increased by 30% "<<endl;
                Defense=(Defense+Defense*0.3);
            }
            else if((Player=="Knight"||Player=="knight")&&temp==2)
            {
                if(Health==120||Health>120)
                {
                    cout<<"Your health is already 120! Your health wont be regenerated! "<<endl;
                }
                else
                {
                    cout<<"You activated regenerate health! Your health is regenerated by 40% "<<endl;
                    Health=Health * skill2DMGPlayer+Health;
                    cout<<"Your current health is : "<<Health<<endl;
                }
            }
            else if((Player=="Knight"||Player=="knight")&&temp==3)
            {
                cout<<"You have used Shield Bash "<<endl;
                cout<<"Enemy takes "<<(skill3DMGPlayer-DefenseE)<<" damage\n"<<endl;
                HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                if(HealthE<=0)
                    {
                        cout<<"Enemy has died\n"<<endl;
                    }
                else
                    {
                        cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                    }

            }
            else if((Player=="Knight"||Player=="knight")&&temp==4)
            {
                cout<<"You have used Spear Throw! "<<endl;
                cout<<"Enemy takes "<<skill3DMGPlayer-DefenseE<<" damage\n"<<endl;
                HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                if(HealthE<=0)
                    {
                        cout<<"Enemy has died\n"<<endl;
                    }
                else
                    {
                        cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                    }

            }
            if ((Player=="Mage"||Player=="mage")&&temp==1)
            {
                cout<<"You activated Magic Up! Your magic is increased by 25% "<<endl;
                skill3DMGPlayer= 0.25*skill3DMGPlayer+skill3DMGPlayer;
                skill4DMGPlayer= 0.25*skill4DMGPlayer+skill4DMGPlayer;
            }
            else if((Player=="Mage"||Player=="mage")&&temp==2)
            {
                Magic=0.35*Magic+Magic;
                cout<<"You activated Magic Penetration ! Your magic is increased by 35% "<<endl;
                skill3DMGPlayer=0.35*skill3DMGPlayer+skill3DMGPlayer;
                skill4DMGPlayer=0.35*skill4DMGPlayer+skill4DMGPlayer;
            }
            else if((Player=="Mage"||Player=="mage")&&temp==3)
            {
                cout<<"You have used Fireball! "<<endl;
                cout<<"Enemy takes "<<(skill3DMGPlayer-DefenseE)<<" damage\n"<<endl;
                HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                    if(HealthE<=0)
                    {
                        cout<<"Enemy has died\n"<<endl;
                    }
                    else
                    {
                        cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                    }

                }
            else if((Player=="Mage"||Player=="mage")&&temp==4)
            {
                cout<<"You have used Wind Shot! "<<endl;
                cout<<"Enemy takes "<<skill3DMGPlayer-DefenseE<<" damage\n"<<endl;
                    HealthE=HealthE-(skill3DMGPlayer-DefenseE);
                        if(HealthE<=0)
                        {
                            cout<<"Enemy has died\n"<<endl;
                        }
                        else
                        {


                            cout<<"Enemy has "<<HealthE<<" health left!\n"<<endl;
                        }


            }
        if(HealthE<=0)
            {
                cout<<"Enemy has died\n\n"<<endl;
            }
        else
            {

            if(TombEnemy=="Skeleton")
            {
                srand(time(NULL));
                cout<<"\n\nEnemy Skeleton has attacked back using Basic Attack!\n"<<endl;
                if(Defense>=skill1DMGEnemy)
                {
                cout<<"Your defense is too high u only take 5 damage\n"<<endl;
                Health=Health-5;
                }
                else
                {
                Health=Health-(skill1DMGEnemy-Defense);
                }
                cout<<"You have : "<<Health<<" health left"<<endl;
            }
            else if(TombEnemy=="DeathKnight")
            {
                string temp4;
                srand(time(NULL));
                temp4 = ar2[rand()%2];
                cout<<"Enemy Death Knight has attacked using "<<temp4<<"."<<endl;
                if(temp4=="Basic Attack")
                {
                    if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else{
                        Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp4=="Frost Shield")
                {
                    if(Defense>skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if(TombEnemy=="Lich")
            {
                string temp3;
                srand(time(NULL));
                temp3 = ar2[rand()%2];
                cout<<"Enemy Lich has attacked using "<<temp3<<"."<<endl;
                if(temp3=="Basic Attack")
                {
                    if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                      else{
                        Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp3=="Crystal Lance")
                {
                     if(Defense>=skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if(TombEnemy=="Necromancer")
            {
                string temp2;
                srand(time(NULL));
                temp2 = ar2[rand()%3];
                cout<<"Enemy Necromancer has attacked using "<<temp2<<"."<<endl;
                if(temp2=="Basic Attack")
                {
                     if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp2=="Frost Bite")
                {
                     if(Defense>=skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp2=="Raise Zombie")
                {
                     if(Defense>=skill3DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill3DMGEnemy-Defense);
                        cout<<"You took "<<skill3DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if (DesertEnemy=="Mummy")
            {
             string temp7;
                srand(time(NULL));
                temp7 = ar2[rand()%2];
                cout<<"Enemy Mummy has attacked using "<<temp7<<"."<<endl;
                if(temp7=="Basic Attack")
                {
                    if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else{
                        Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp7=="Bandage Wrap")
                {
                    if(Defense>skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if(DesertEnemy=="Alligator")
            {
            string temp11;
                srand(time(NULL));
                temp11 = ar2[rand()%2];
                cout<<"Enemy Alligator has attacked using "<<temp11<<"."<<endl;
                if(temp11=="Tail Whip")
                {
                    if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else{
                        Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp11=="Jaw Breaker")
                {
                    if(Defense>=skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if (DesertEnemy=="Thief")
            {
            string temp20;
                srand(time(NULL));
                temp20 = ar2[rand()%2];
                cout<<"Enemy Thief has attacked using "<<temp20<<"."<<endl;
                if(temp20=="Basic Attack")
                {
                    if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else{
                        Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp20=="Knife Throw")
                {
                    if(Defense>skill2DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill2DMGEnemy-Defense);
                        cout<<"You took "<<skill2DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
            else if (DesertEnemy=="Scorpion")
            {
            string temp31;
                srand(time(NULL));
                temp31 = ar2[rand()%3];
                cout<<"Enemy Scorpion has attacked using "<<temp31<<"."<<endl;
                if(temp31=="Tail Swipe")
                {
                     if(Defense>=skill1DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill1DMGEnemy-Defense);
                        cout<<"You took "<<skill1DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
                else if(temp31=="UnderGround")
                {
                     if(HealthE+skill2DMGEnemy>1000)
                     {
                         cout<<"Scorpion is at max HP , you may want to attack soon!\n\n";
                     }
                     else
                     {
                        HealthE=HealthE+skill2DMGEnemy;
                     }
                }
                else if(temp31=="Poison Stinger")
                {
                     if(Defense>=skill3DMGEnemy)
                    {
                        Health=Health-5;
                        cout<<"You took 5 damage. You have : "<<Health<<" left."<<endl;
                    }
                    else
                    {
                         Health=Health-(skill3DMGEnemy-Defense);
                        cout<<"You took "<<skill3DMGEnemy-Defense<<" damage"<<endl;
                        cout<<"You have : "<<Health<<" health left"<<endl;
                    }
                }
            }
        }
        if(Health<=0)
        {
            cout<<"You died \n\n";
            system("pause");
            break;
        }
            }

        cout<<"NEXT BATTLE IS ABOUT TO BEGIN!\n\n"<<endl;
        system("pause");
        cout<<"--------------------------------------------------------------------"<<endl;
    }
void EnemyStats(string a)
{

        if (a=="Skeleton")
        {
            HealthE = 100;
            AttackE = 30;
            LuckE = 0;
            MagicE = 5;
            DefenseE = 10;
            skill1DMGEnemy=Attack*0.3 +15;
            skill2DMGEnemy=0;
            skill3DMGEnemy=0;
            std::string EnemySkillsArr[]={"Basic Attack"};
            Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
        }
        else if (a=="Lich")
        {
            HealthE = 150;
            AttackE = 5;
            LuckE = 5;
            MagicE = 41;
            DefenseE = 5;
            skill1DMGEnemy = 14 + (0.3*AttackE);
            skill2DMGEnemy = (MagicE*0.6) + 10;
            std::string EnemySkillsArr[]={"Basic Attack","Crystal Lance"};
            Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
        }

        else if (a=="DeathKnight")
        {
            HealthE = 200;
            AttackE = 37;
            LuckE = 0;
            MagicE = 5;
            DefenseE = 41;
            skill1DMGEnemy = 20+ (AttackE*0.4);
            Defense = DefenseE + (DefenseE*0.4);
            skill2DMGEnemy = (DefenseE*0.8) + 15;
            std::string EnemySkillsArr[]={"Basic Attack","Frost Shield"};
            Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
        }
        else if (a=="Necromancer")
        {
            HealthE = 700;
            AttackE = 35;
            LuckE=0;
            MagicE = 100;
            DefenseE = 5;
            skill1DMGEnemy = 2.4*(7 + (0.1*AttackE));
            skill2DMGEnemy = 10 + (0.5*MagicE);
            skill3DMGEnemy= 8 + (0.3*AttackE);
            std::string EnemySkillsArr[]={"Basic Attack","Frost Bite","Raise Zombie"};
            Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
        }
	else if (a=="Thief")
	{
	    HealthE = 240;
            AttackE = 30;
            LuckE=0;
            MagicE = 40;
            DefenseE = 5;
            skill1DMGEnemy = 0.9*(7 + (0.5*AttackE));
            skill2DMGEnemy = 10 + (0.7*MagicE+0.2*AttackE);
	    std::string EnemySkillsArr[]={"Basic Attack","Knife Throw"};
	    Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
	}
	else if(a=="Mummy")
	{
	    HealthE = 313;
            AttackE = 21;
            LuckE=0;
            MagicE = 31;
            DefenseE = 5;
            skill1DMGEnemy = 1.3*AttackE+AttackE;
            skill2DMGEnemy = 11+AttackE+(0.3*MagicE);
	    std::string EnemySkillsArr[]={"Basic Attack","Bandage Wrap"};
	    Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
	}
	else if(a=="Alligator")
	{
	    HealthE = 360;
            AttackE = 22;
            LuckE=0;
            MagicE = 22;
            DefenseE = 5;
            skill1DMGEnemy = 1.1*MagicE+0.1*AttackE;
            skill2DMGEnemy = 10+AttackE+(0.4*AttackE);
	    std::string EnemySkillsArr[]={"Tail Whip","Jaw Breaker"};
	    Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
	}
	else if(a=="Scorpion")
	{
 	        HealthE = 1000;
            AttackE = 20;
            LuckE=0;
            MagicE = 70;
            DefenseE = 5;
            skill1DMGEnemy = 0.1*MagicE+2.3*AttackE;
            skill2DMGEnemy = 0.3*MagicE+220;
	    skill3DMGEnemy = 1.8*MagicE+0.01*AttackE;
	    std::string EnemySkillsArr[]={"Tail Swipe","Underground","Poison Stinger"};
	    Battle(Health,Defense,Attack,Magic,HealthE,DefenseE,AttackE,MagicE,skill1DMGPlayer,skill2DMGPlayer,skill3DMGPlayer
                   ,skill4DMGPlayer,skill1DMGEnemy,skill2DMGEnemy,skill3DMGEnemy,PlayerSkillsArr,EnemySkillsArr);
    }
}
void Enemies(int a)
    {
        if (a==1)
        {
            string random;
            int temp;
            std::string tombEnemies[] = {"Skeleton","Lich","DeathKnight"};
            cout<<"------------------------------------------------------------- \n\n"<<endl;
            cout<<"Here begins your tomb exploration! "<<endl;
            srand(time(NULL));
            for(int i =0;i<=4;i++)
            {
                random = tombEnemies[rand() % 3];
                cout<<"Your enemy will be a : ";
                cout<<random<<"! \n\n";
                TombEnemy=random;
                EnemyStats(TombEnemy);
            }
            TombEnemy="Necromancer";
            cout<<" "<<endl;
            cout<<"You are facing the Necromancer now! Good luck."<<endl;
            EnemyStats(TombEnemy);
        }
        else if (a==2)
        {
            string random;
            int temp;
            std::string desertEnemies[] = {"Mummy","Alligator","Thief"};
            cout<<"------------------------------------------------------------- \n\n"<<endl;
            cout<<"Here begins your tomb exploration! "<<endl;
            srand(time(NULL));
            for(int i =0;i<=4;i++)
            {
                random = desertEnemies[rand() % 3];
                cout<<"Your enemy will be a : ";
                cout<<random<<"! \n\n";
                DesertEnemy=random;
                EnemyStats(DesertEnemy);
            }
            DesertEnemy="Scorpion";
            cout<<" "<<endl;
            cout<<"You are facing the Scorpion now! Good luck."<<endl;
            EnemyStats(DesertEnemy);

    }
    }
void Skills(string a)
    {
        int temp;

        if (a=="Assassin"||a=="assassin")
        {
            cout<<"These are the assassin skills\n\n";
            skill1="1. Attack up";
            skill2="2. Regenerate HP";
            skill3="3. Heart stab";
            skill4="4. Throw Dagger\n\n";
            std::string kek[4]={skill1,skill2,skill3,skill4};
            cout<<skill1<<"\n"<<skill2<<"\n"<<skill3<<"\n"<<skill4;
            skill1DMGPlayer=0.5;
            skill2DMGPlayer=0.4;
            skill3DMGPlayer=40;
            skill4DMGPlayer=25;
            for(int i=0;i<4;i++)
            {
                PlayerSkillsArr[i]=kek[i];
            }
        }
        else if (a=="Mage"||a=="mage")
        {
            cout<<"These are the mage skills\n\n";
            skill1="1. Magic up";
            skill2="2. Magic penetration up";
            skill3="3. Fireball";
            skill4="4. Wind Shot\n\n";
            std::string kek[4]={skill1,skill2,skill3,skill4};
            cout<<skill1<<"\n"<<skill2<<"\n"<<skill3<<"\n"<<skill4;
            skill1DMGPlayer=0.25;
            skill2DMGPlayer=0.35;
            skill3DMGPlayer=35;
            skill4DMGPlayer=30;
            for(int i=0;i<4;i++)
            {
                PlayerSkillsArr[i]=kek[i];
            }
        }
        else if(a=="Knight"||a=="knight")
        {
            cout<<"These are the knight skills \n\n";
            skill1="1. Defense up";
            skill2="2. Regenerate health";
            skill3="3. Shield bash";
            skill4="4. Spear throw\n\n";
            std::string kek[4]={skill1,skill2,skill3,skill4};
            cout<<skill1<<"\n"<<skill2<<"\n"<<skill3<<"\n"<<skill4;
            skill1DMGPlayer=0.35;
            skill2DMGPlayer=0.4;
            skill3DMGPlayer=30;
            skill4DMGPlayer=20;
            for(int i=0;i<4;i++)
            {
                PlayerSkillsArr[i]=kek[i];
            }
        }
        cout<<"Where would u like to spawn a tomb or a desert? Press 1 for tomb or 2 for desert.\n\n";
        cout<<"Insight-------->Desert is much harder than tomb\n\n";
        cin>>temp;
        if(temp==1)
        {
            cout<<"Welcome to the tomb of Nazaric . This dungeon is overpopulated with skeletons and dead humanoid enemies.";
            cout<<"\n\nYou will eventually face the bosses of the tomb so be prepared.";
            cout<<"\n\nThe first boss will be a necromancer which is considered the weakest boss of the dungeon.";
            cout<<"If you manage to beat the \nnecromancer , u can advance further into the tomb. Good luck!\n\n";
            system("pause");
        }
        else if(temp==2)
        {
            cout<<"Welcome to the Black Desert! This place is populated from humanoid and non humanoid creatures";
            cout<<"\n\nYou will be fighting for your life in this place. And at the end of the dungeon a scorpion awaits.";
            cout<<"\n\nOnce you beat the scorpion you may venture further into the desert";
            cout<<"\n\nLegendary Items and Legendary bosses await you. Good luck!\n\n";
            system("pause");
        }
        Enemies(temp);

    }
void Rpg(string x , string y, double r,int c,int b,int f,double g)
    {
         Player = x;
         Role = y;
         Health = r;
         Luck = b;
         Attack = c;
         Magic = f;
         Defense = g;
         Skills(Player);
    }

int main(){
const int Health2=200;
const int Attack2=30;
const int Luck2=15;
const int Magic2=0;
const int Defense2=30;

string meme;
string meme2;
cout<<"\nPlease select the name of your character.\n\n";
cin>>meme;
cout<<"\nWelcome User "<<meme<<". Enjoy your dungeon runs!\n\n";
cout<<"Please select the role u want to play as. Assassin/Knight/Mage.\n\n";
cin>>meme2;
if(meme2=="Assassin"||meme2=="assassin")
{
    Rpg (meme2,meme,Health2+20,Attack2+15,Luck2+15,Magic2,Defense2+10);
}
else if (meme2=="Mage"|| meme2=="mage")
{
    Rpg (meme2,meme,Health2+10,Attack2+5,Luck2+10,Magic2+30,Defense2+10);
}
else if(meme2=="Knight"||meme2=="knight")
{
    Rpg (meme2,meme,Health2+35,Attack2+10,Luck2+5,Magic2+5,Defense2+15);
}
else
{
        cout<<"Please select one of those 3 classes or the game wont start.";
        main();
}
cout<<"\n";
system("pause");

return 0;
}
